version: '3'
services:
    django:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        environment:
            - DEBUG=1
        ports:
            - "8000:8000"
        container_name: digit_project
